### ISSUE TITLE
Warning message about '%dorng%' vs '%dopar%' when run in parallel

### ISSUE THREAD

**Issue by dansmith01** [SchlossLab/mikropml#283] opened 2021-11-11 21:08 UTC
I was working through the introductory vignette and am getting warning messages about statistically unsound random numbers:

```r
remotes::install_github("SchlossLab/mikropml")
library(mikropml)
doFuture::registerDoFuture()
future::plan(future::multisession, workers = 2)
results <- run_ml(otu_mini_bin, 'glmnet', outcome_colname = 'dx', seed = 2019)
```
```
Using 'dx' as the outcome column.
Training the model...
Training complete.
Warning messages:
1: UNRELIABLE VALUE: One of the foreach() iterations (‘doFuture-1’) unexpectedly generated random numbers without declaring so. There is a risk that those random numbers are not statistically sound and the overall results might be invalid. To fix this, use '%dorng%' from the 'doRNG' package instead of '%dopar%'. This ensures that proper, parallel-safe random numbers are produced via the L'Ecuyer-CMRG method. To disable this check, set option 'future.rng.onMisuse' to "ignore". 
2: UNRELIABLE VALUE: One of the foreach() iterations (‘doFuture-2’) unexpectedly generated random numbers without declaring so. There is a risk that those random numbers are not statistically sound and the overall results might be invalid. To fix this, use '%dorng%' from the 'doRNG' package instead of '%dopar%'. This ensures that proper, parallel-safe random numbers are produced via the L'Ecuyer-CMRG method. To disable this check, set option 'future.rng.onMisuse' to "ignore". 
3: In (function (w)  : `caret::train()` issued the following warning:
 
simpleWarning in nominalTrainWorkflow(x = x, y = y, wts = weights, info = trainInfo, : There were missing values in resampled performance measures.

This warning usually means that the model didn't converge in some cross-validation folds because it is predicting something close to a constant. As a result, certain performance metrics can't be calculated. This suggests that some of the hyperparameters chosen are doing very poorly
```

I'm using R 4.1.1 on Windows 10.

**Comment by kelly-sovacool** [comment] 2021-11-11 23:21
I was able to reproduce your warning message on macOS both within and outside RStudio. However, if I use multicore instead of multisession I _don't_ get this warning. For now, I'd suggest using multicore instead of multisession if possible while we figure out the underlying cause of this. We haven't used `foreach()` in this package so I suspect the problem is within `caret::train()`.

**Comment by kelly-sovacool** [comment] 2022-10-24 15:47
I'm closing this issue as using the multicore future plan outside of RStudio is a good workaround, and figuring out how to get multisession to work depends on factors outside our control.

**Closed by kelly-sovacool** 2022-10-24 15:47 UTC
